using System.Collections.Generic;
using System.IO;
using System.Linq;
using GalaQuest.Gear;
using UnityEditor;
using UnityEditor.Animations;
using UnityEditor.SceneManagement;
using UnityEngine;

namespace GalaQuest.Gear.Editor
{
    /// <summary>
    /// Creates the workbench scene: GQ_HERO_V1, neutral lighting, the Head Fit Proxy visualizer, every
    /// GearItemDefinition mounted through the ordinary <see cref="GearMounter"/>, and an Animator wired
    /// to GQ_HERO_V1's own clips.
    ///
    /// The same scene is the Owner's fitting surface in Edit Mode and the PlayMode animation-sweep
    /// fixture, so the pose the Owner accepted is the pose the gates actually swept.
    ///
    /// Deterministic and regenerable -- the scene is a view, not authority. Item fits live in
    /// GearItemDefinition assets, so deleting and rebuilding this scene loses nothing.
    /// </summary>
    public static class GearWorkbenchSceneBuilder
    {
        public const string ControllerPath = "Assets/GalaQuest/Gear/Definitions/GQ_HERO_V1_Poses.controller";

        /// <summary>Generated by tools/unity-migration/export-hero-anatomy-regions.mjs.</summary>
        public const string AnatomyRegionMapPath =
            "Assets/GalaQuest/Gear/Definitions/HeroAnatomyRegions.json";

        [MenuItem("GalaQuest/Gear/Rebuild Gear Workbench scene")]
        public static void Build()
        {
            var heroPrefab = AssetDatabase.LoadAssetAtPath<GameObject>(GearHeroAuthoring.HeroPrefabPath);
            if (heroPrefab == null)
            {
                GearHeroAuthoring.RebuildAll();
                heroPrefab = AssetDatabase.LoadAssetAtPath<GameObject>(GearHeroAuthoring.HeroPrefabPath);
            }

            if (heroPrefab == null)
                throw new FileNotFoundException("GQ_HERO_V1 prefab missing: " + GearHeroAuthoring.HeroPrefabPath);

            var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

            var key = new GameObject("Workbench Key Light");
            var keyLight = key.AddComponent<Light>();
            keyLight.type = LightType.Directional;
            keyLight.intensity = 1.1f;
            keyLight.shadows = LightShadows.Soft;
            key.transform.rotation = Quaternion.Euler(35f, 150f, 0f);

            var fill = new GameObject("Workbench Fill Light");
            var fillLight = fill.AddComponent<Light>();
            fillLight.type = LightType.Directional;
            fillLight.intensity = 0.35f;
            fillLight.shadows = LightShadows.None;
            fill.transform.rotation = Quaternion.Euler(15f, -40f, 0f);

            var hero = (GameObject)PrefabUtility.InstantiatePrefab(heroPrefab);
            hero.transform.position = Vector3.zero;
            hero.transform.rotation = Quaternion.identity;

            var proxy = AssetDatabase.LoadAssetAtPath<HeadFitProxy>(GearHeroAuthoring.HeadProxyPath);
            var head = GearHeroAuthoring.FindDescendant(hero.transform, GearSocketIds.HeadBone);
            if (proxy != null && head != null)
            {
                hero.AddComponent<HeadFitProxyVisualizer>().Configure(proxy, head);
            }

            var body = hero.GetComponentInChildren<SkinnedMeshRenderer>(true);
            var regionMap = AssetDatabase.LoadAssetAtPath<TextAsset>(AnatomyRegionMapPath);
            if (body != null && regionMap != null)
            {
                hero.AddComponent<AnatomyCoveragePreview>().Configure(body, regionMap);
            }
            else
            {
                Debug.LogWarning("Anatomy coverage preview unavailable: " +
                                 (body == null ? "no Hero SkinnedMeshRenderer" : "no region map at " + AnatomyRegionMapPath));
            }

            var controller = BuildPoseController(out var stateNames);
            var animator = hero.GetComponent<Animator>();
            if (animator == null) animator = hero.AddComponent<Animator>();
            animator.runtimeAnimatorController = controller;
            animator.applyRootMotion = false;
            animator.cullingMode = AnimatorCullingMode.AlwaysAnimate;

            HideBakedAtlasGear(hero);
            MountAllDefinitions(hero);

            var rig = hero.AddComponent<GearFitProofRig>();
            rig.Configure(hero.transform, proxy, animator, stateNames);

            Directory.CreateDirectory(Path.GetDirectoryName(GearWorkbenchWindow.ScenePath));
            EditorSceneManager.SaveScene(scene, GearWorkbenchWindow.ScenePath);
            UnregisterBuildScene(GearWorkbenchWindow.ScenePath);
            AssetDatabase.Refresh();
            Debug.Log("GalaQuest gear workbench scene rebuilt at " + GearWorkbenchWindow.ScenePath + ".");
        }

        /// <summary>
        /// The shipped Hero atlas has the Tier 2 sword and shield baked into it as their own mesh nodes,
        /// because public/src/character/gear.js re-parents those merged nodes rather than loading files.
        /// In the workbench they would render alongside the item being fitted, so the scene hides them.
        ///
        /// This is a VIEW decision in a regenerable scene. The GQ_HERO_V1 prefab and the shipped atlas are
        /// untouched -- nothing here changes what the Hero is.
        /// </summary>
        private static void HideBakedAtlasGear(GameObject hero)
        {
            foreach (var bakedName in new[] { "shield_ironwood", "sword_ironwood" })
            {
                var baked = GearHeroAuthoring.FindDescendant(hero.transform, bakedName);
                if (baked == null) continue;
                baked.gameObject.SetActive(false);
                Debug.Log("Workbench scene hid the baked atlas node '" + bakedName +
                          "' so the mounted item is judged alone.");
            }
        }

        private static void MountAllDefinitions(GameObject hero)
        {
            var definitions = AssetDatabase.FindAssets("t:GearItemDefinition")
                .Select(AssetDatabase.GUIDToAssetPath)
                .Select(AssetDatabase.LoadAssetAtPath<GearItemDefinition>)
                .Where(asset => asset != null && asset.SourceModel != null)
                .OrderBy(asset => asset.SemanticId);

            foreach (var definition in definitions)
            {
                try
                {
                    var mounted = GearMounter.Mount(hero.transform, definition);
                    mounted.AddComponent<GearMountedItem>().Configure(definition);
                }
                catch (GearMounter.MountFailure failure)
                {
                    Debug.LogWarning("Skipped " + definition.SemanticId + " in the workbench scene: " +
                                     failure.Message);
                }
            }
        }

        private static AnimatorController BuildPoseController(out string[] stateNames)
        {
            var clips = AssetDatabase.LoadAllAssetsAtPath(GearHeroAuthoring.HeroModelPath)
                .OfType<AnimationClip>()
                .Where(clip => !clip.name.StartsWith("__preview__"))
                .OrderBy(clip => clip.name)
                .ToArray();

            Directory.CreateDirectory(Path.GetDirectoryName(ControllerPath));
            if (File.Exists(ControllerPath)) AssetDatabase.DeleteAsset(ControllerPath);

            var controller = AnimatorController.CreateAnimatorControllerAtPath(ControllerPath);
            var stateMachine = controller.layers[0].stateMachine;

            var names = new List<string>();
            foreach (var clip in clips)
            {
                var state = stateMachine.AddState(clip.name);
                state.motion = clip;
                state.writeDefaultValues = true;
                names.Add(clip.name);
            }

            if (clips.Length > 0)
            {
                stateMachine.defaultState = stateMachine.states[0].state;
            }

            EditorUtility.SetDirty(controller);
            stateNames = names.ToArray();
            return controller;
        }

        /// <summary>
        /// Keep the workbench OUT of player Build Settings.
        ///
        /// It is Editor authoring infrastructure, not a player destination: shipping it would put an
        /// authoring scene, the Hero prefab and every gear model into the Windows and WebGL players.
        /// An earlier revision registered it as an enabled build scene so a PlayMode test could load it
        /// by name; the test now loads it by path through EditorSceneManager instead.
        ///
        /// This only ever removes THIS path. Emberworks, VisibleArmorProof, MigrationProof and
        /// SampleScene are untouched.
        /// </summary>
        private static void UnregisterBuildScene(string scenePath)
        {
            var scenes = EditorBuildSettings.scenes.ToList();
            var remaining = scenes.Where(scene => scene.path != scenePath).ToArray();
            if (remaining.Length == scenes.Count) return;

            EditorBuildSettings.scenes = remaining;
            Debug.Log("Removed " + scenePath + " from player Build Settings; " +
                      remaining.Length + " build scene(s) remain.");
        }
    }
}
