using System.Collections.Generic;
using System.IO;
using System.Linq;
using GalaQuest.Gear;
using UnityEditor;
using UnityEngine;

namespace GalaQuest.Gear.Editor
{
    /// <summary>
    /// Builds the two authoring assets every gear item depends on:
    ///
    ///   1. GQ_HERO_V1.prefab -- the imported Hero with named <see cref="GearSocket"/> children under the
    ///      bones the shipped Three.js mounts already use. Sockets are ordinary Transforms; nothing here
    ///      invents a GalaQuest attachment algorithm.
    ///
    ///   2. HeadFitProxy.asset -- measured from GQ_HERO_V1's own anatomy, never from a helmet.
    ///
    /// Both are regenerated by one menu item so the derivation is reproducible and reviewable rather than
    /// a one-off hand edit.
    /// </summary>
    public static class GearHeroAuthoring
    {
        public const string HeroModelPath =
            "Assets/GalaQuest/Migration/SourceAssets/VisibleArmor/Hero.fbx";

        public const string HeroPrefabPath =
            "Assets/GalaQuest/Gear/Prefabs/GQ_HERO_V1.prefab";

        public const string HeadProxyPath =
            "Assets/GalaQuest/Gear/Definitions/HeadFitProxy.asset";

        /// <summary>Recorded in unity/.../Migration/VisibleArmorProvenance.json for the Hero source GLB.</summary>
        public const string HeroSourceRepoPath = "public/assets/hero/hero_lod1_ironwood_atlas.glb";

        public const string HeroSourceSha256 =
            "082fc24b8fe181a6b428a3226471e56cafbb71edd6cacbfdcfd82651dfa61679";

        [MenuItem("GalaQuest/Gear/Rebuild GQ_HERO_V1 and Head Fit Proxy")]
        public static void RebuildAll()
        {
            var prefab = BuildHeroPrefab();
            BuildHeadFitProxy(prefab);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log("GalaQuest gear authoring rebuilt: " + HeroPrefabPath + " and " + HeadProxyPath);
        }

        public static GameObject BuildHeroPrefab()
        {
            var model = AssetDatabase.LoadAssetAtPath<GameObject>(HeroModelPath);
            if (model == null)
                throw new FileNotFoundException("GQ_HERO_V1 source model missing: " + HeroModelPath);

            var instance = (GameObject)PrefabUtility.InstantiatePrefab(model);
            try
            {
                instance.name = "GQ_HERO_V1";

                foreach (var (socketId, boneName) in GearSocketIds.Authored)
                {
                    var bone = FindDescendant(instance.transform, boneName);
                    if (bone == null)
                        throw new MissingReferenceException(
                            "GQ_HERO_V1 has no bone '" + boneName + "' for socket '" + socketId + "'.");

                    var existing = bone.GetComponentsInChildren<GearSocket>(true)
                        .FirstOrDefault(s => s.SocketId == socketId);
                    if (existing != null) continue;

                    var socketObject = new GameObject("Socket_" + socketId);
                    socketObject.transform.SetParent(bone, false);
                    socketObject.transform.localPosition = Vector3.zero;
                    socketObject.transform.localRotation = Quaternion.identity;
                    socketObject.transform.localScale = Vector3.one;
                    socketObject.AddComponent<GearSocket>().Configure(socketId, boneName);
                }

                Directory.CreateDirectory(Path.GetDirectoryName(HeroPrefabPath));
                return PrefabUtility.SaveAsPrefabAsset(instance, HeroPrefabPath);
            }
            finally
            {
                Object.DestroyImmediate(instance);
            }
        }

        public static HeadFitProxy BuildHeadFitProxy(GameObject heroPrefab)
        {
            if (heroPrefab == null)
                heroPrefab = AssetDatabase.LoadAssetAtPath<GameObject>(HeroPrefabPath);
            if (heroPrefab == null)
                throw new FileNotFoundException("GQ_HERO_V1 prefab missing: " + HeroPrefabPath);

            var instance = (GameObject)PrefabUtility.InstantiatePrefab(heroPrefab);
            try
            {
                var head = FindDescendant(instance.transform, GearSocketIds.HeadBone);
                var crownHelper = FindDescendant(instance.transform, GearSocketIds.CrownHelperBone);
                var faceHelper = FindDescendant(instance.transform, GearSocketIds.FaceHelperBone);

                if (head == null || crownHelper == null || faceHelper == null)
                {
                    throw new MissingReferenceException(
                        "GQ_HERO_V1 is missing Head/" + GearSocketIds.CrownHelperBone + "/" +
                        GearSocketIds.FaceHelperBone + "; the Head Fit Proxy cannot be measured.");
                }

                var crownLocal = head.InverseTransformPoint(crownHelper.position);
                var faceLocal = head.InverseTransformPoint(faceHelper.position);
                var skullRadius = MeasureSkullRadius(instance, head, crownLocal);

                var proxy = AssetDatabase.LoadAssetAtPath<HeadFitProxy>(HeadProxyPath);
                var created = proxy == null;
                if (created) proxy = ScriptableObject.CreateInstance<HeadFitProxy>();

                proxy.ConfigureMeasured(
                    crownLocal,
                    faceLocal,
                    skullRadius,
                    HeroSourceRepoPath,
                    HeroSourceSha256,
                    "crown from the head_end helper joint; faceAnchor from the headfront helper joint; " +
                    "skullRadius = 95th-percentile lateral radius of Head-dominated vertices about the " +
                    "head axis, measured on the bind pose. No helmet participated in this measurement.");

                if (created)
                {
                    // Seeded from the Hero's own proportions, then adjusted by looking at the Hero in
                    // Unity. The eyes are painted into the atlas, so no mesh measurement can place them.
                    var eyeHeight = crownLocal.magnitude * DefaultEyeLineFractionOfHead;
                    var eyeLine = crownLocal.normalized * eyeHeight +
                                  faceLocal.normalized * (skullRadius * 0.9f);
                    proxy.ConfigureAuthored(eyeLine, DefaultEyeClearanceRadius, DefaultMaxCrownGap);

                    Directory.CreateDirectory(Path.GetDirectoryName(HeadProxyPath));
                    AssetDatabase.CreateAsset(proxy, HeadProxyPath);
                }

                EditorUtility.SetDirty(proxy);
                return proxy;
            }
            finally
            {
                Object.DestroyImmediate(instance);
            }
        }

        /// <summary>
        /// Where the Hero's eye line sits as a fraction of head-bone-to-crown height.
        ///
        /// This seeds the authored value only; the eyes are painted into the Hero atlas, so no mesh
        /// measurement can place them and the number has to come from looking at the Hero.
        ///
        /// Measured off a neutral Unity render of the bare Hero head at this project's own inspection
        /// framing: the eye centres sit about 0.213 m above the Head bone on a head that is 0.389 m from
        /// bone to crown helper. docs/foundry/gear/tier3_fit.json's older Blender-space figure (eyes at
        /// 1.330 world, i.e. 0.605 of head height) sits about 23 mm higher; the render is preferred
        /// because it is measured in the engine the gear is fitted in. Neither is authority -- the value
        /// lives in the asset so the Owner can correct it by looking.
        /// </summary>
        public const float DefaultEyeLineFractionOfHead = 0.548f;

        public const float DefaultEyeClearanceRadius = 0.08f;
        public const float DefaultMaxCrownGap = 0.03f;

        private static float MeasureSkullRadius(GameObject heroInstance, Transform head, Vector3 crownLocal)
        {
            var renderer = heroInstance.GetComponentInChildren<SkinnedMeshRenderer>(true);
            if (renderer == null || renderer.sharedMesh == null) return 0f;

            var mesh = renderer.sharedMesh;
            var bones = renderer.bones;
            var headIndex = -1;
            for (var i = 0; i < bones.Length; i++)
            {
                if (bones[i] != null && bones[i] == head) { headIndex = i; break; }
            }
            if (headIndex < 0) return 0f;

            var baked = new Mesh();
            try
            {
                renderer.BakeMesh(baked, true);
                var posed = baked.vertices;
                var weights = mesh.boneWeights;
                if (weights.Length != posed.Length) return 0f;

                var axis = crownLocal.sqrMagnitude > 1e-8f ? crownLocal.normalized : Vector3.up;
                var radii = new List<float>();

                for (var i = 0; i < posed.Length; i++)
                {
                    if (!DominatedBy(weights[i], headIndex)) continue;
                    var world = renderer.transform.TransformPoint(posed[i]);
                    var local = head.InverseTransformPoint(world);
                    var height = Vector3.Dot(local, axis);
                    radii.Add((local - axis * height).magnitude);
                }

                if (radii.Count == 0) return 0f;
                radii.Sort();
                // 95th percentile rather than the maximum: the maximum is whatever hair spike sticks out
                // furthest, and the proxy is a seat reference for the skull, not a shell around the hair.
                var index = Mathf.Clamp(Mathf.RoundToInt((radii.Count - 1) * 0.95f), 0, radii.Count - 1);
                return radii[index];
            }
            finally
            {
                Object.DestroyImmediate(baked);
            }
        }

        private static bool DominatedBy(BoneWeight weight, int boneIndex)
        {
            var total = 0f;
            if (weight.boneIndex0 == boneIndex) total += weight.weight0;
            if (weight.boneIndex1 == boneIndex) total += weight.weight1;
            if (weight.boneIndex2 == boneIndex) total += weight.weight2;
            if (weight.boneIndex3 == boneIndex) total += weight.weight3;
            return total > 0.5f;
        }

        public static Transform FindDescendant(Transform root, string name)
        {
            foreach (var transform in root.GetComponentsInChildren<Transform>(true))
                if (transform.name == name) return transform;
            return null;
        }
    }
}
