export const CROPS = [
  { id: 'carrot', name: 'Carrot', growSeconds: 8, sellPrice: 1, color: '#f28c28', element: null, distinctive: false },
  { id: 'wheat', name: 'Wheat', growSeconds: 10, sellPrice: 1, color: '#f5d061', element: null, distinctive: false },
  { id: 'pumpkin', name: 'Pumpkin', growSeconds: 14, sellPrice: 3, color: '#ff8c00', element: null, distinctive: false },
  { id: 'sunberry', name: 'Sunberry', growSeconds: 16, sellPrice: 3, color: '#ff5722', element: 'fire', distinctive: true },
  { id: 'dewmelon', name: 'Dewmelon', growSeconds: 18, sellPrice: 3, color: '#4fc3f7', element: 'water', distinctive: true },
  { id: 'glowleaf', name: 'Glowleaf', growSeconds: 20, sellPrice: 4, color: '#8bc34a', element: 'leaf', distinctive: true },
];

export const ARMOR = [
  { id: 'sprout_helmet', name: 'Sprout Helmet', slot: 'helmet', price: 5, color: '#6cc24a', accent: '#2e7d32', set: 'Sprout' },
  { id: 'sprout_chest', name: 'Sprout Vest', slot: 'chest', price: 6, color: '#6cc24a', accent: '#2e7d32', set: 'Sprout' },
  { id: 'sprout_boots', name: 'Sprout Boots', slot: 'boots', price: 5, color: '#6cc24a', accent: '#2e7d32', set: 'Sprout' },
  { id: 'sprout_shield', name: 'Sprout Shield', slot: 'shield', price: 8, color: '#6cc24a', accent: '#2e7d32', set: 'Sprout' },
  { id: 'ember_helmet', name: 'Ember Cap', slot: 'helmet', price: 14, color: '#ff7043', accent: '#bf360c', set: 'Ember' },
  { id: 'ember_chest', name: 'Ember Tunic', slot: 'chest', price: 18, color: '#ff7043', accent: '#bf360c', set: 'Ember' },
  { id: 'ember_boots', name: 'Ember Boots', slot: 'boots', price: 12, color: '#ff7043', accent: '#bf360c', set: 'Ember' },
  { id: 'ember_shield', name: 'Ember Guard', slot: 'shield', price: 20, color: '#ff7043', accent: '#bf360c', set: 'Ember' },
];

export const CREATURES = [
  { id: 'emberpup', name: 'Emberpup', element: 'fire', rarity: 'common', shape: 'round',
    colors: { body: '#ff7043', accent: '#ffd54f' }, blurb: 'Loves warm sunberries.' },
  { id: 'cinderkit', name: 'Cinderkit', element: 'fire', rarity: 'rare', shape: 'tall',
    colors: { body: '#e64a19', accent: '#ffab91' }, blurb: 'Dances near warm stones.' },
  { id: 'flamewhisk', name: 'Flamewhisk', element: 'fire', rarity: 'epic', shape: 'long',
    colors: { body: '#d84315', accent: '#ffcc80' }, blurb: 'Its tail glows brightest.' },
  { id: 'puddlefin', name: 'Puddlefin', element: 'water', rarity: 'common', shape: 'round',
    colors: { body: '#4fc3f7', accent: '#b3e5fc' }, blurb: 'Splashes happily in dewmelons.' },
  { id: 'splashpuff', name: 'Splashpuff', element: 'water', rarity: 'rare', shape: 'winged',
    colors: { body: '#29b6f6', accent: '#e1f5fe' }, blurb: 'Makes tiny rainbows.' },
  { id: 'tidekit', name: 'Tidekit', element: 'water', rarity: 'epic', shape: 'long',
    colors: { body: '#0288d1', accent: '#81d4fa' }, blurb: 'Hums a quiet wave song.' },
  { id: 'mossbun', name: 'Mossbun', element: 'leaf', rarity: 'common', shape: 'round',
    colors: { body: '#8bc34a', accent: '#f1f8e9' }, blurb: 'Hops between glowleaf patches.' },
  { id: 'fernsprout', name: 'Fernsprout', element: 'leaf', rarity: 'rare', shape: 'tall',
    colors: { body: '#689f38', accent: '#c5e1a5' }, blurb: 'Grows a new leaf daily.' },
  { id: 'bloomtail', name: 'Bloomtail', element: 'leaf', rarity: 'epic', shape: 'long',
    colors: { body: '#558b2f', accent: '#aed581' }, blurb: 'Leaves flowers where it walks.' },
  { id: 'zapkit', name: 'Zapkit', element: 'spark', rarity: 'common', shape: 'round',
    colors: { body: '#ffee58', accent: '#fff9c4' }, blurb: 'Zips around wheat fields.' },
  { id: 'glimmerpup', name: 'Glimmerpup', element: 'spark', rarity: 'rare', shape: 'winged',
    colors: { body: '#fdd835', accent: '#fff176' }, blurb: 'Sparks light up the barn.' },
  { id: 'boltbun', name: 'Boltbun', element: 'spark', rarity: 'epic', shape: 'tall',
    colors: { body: '#f9a825', accent: '#ffecb3' }, blurb: 'Runs faster than Pip.' },
];

export const NPCS = [
  { id: 'pip', name: 'Farmer Pip', color: '#8d6e63', greeting: 'Howdy, farmer!' },
  { id: 'maple', name: 'Maple', color: '#e57373', greeting: 'Hey there, friend!' },
  { id: 'reed', name: 'Reed', color: '#64b5f6', greeting: 'Adventure awaits!' },
];

export const OFFERS = [
  { id: 'pip_carrots', npc: 'pip', band: 'younger', text: 'Three carrots please! I will pay six coins.',
    wants: { carrot: 3 }, coins: 6, teach: 'counting to 10' },
  { id: 'maple_wheat', npc: 'maple', band: 'younger', text: 'Two wheat bundles, please!',
    wants: { wheat: 2 }, coins: 4, teach: 'counting by 2s' },
  { id: 'pip_pumpkins_big', npc: 'pip', band: 'younger', text: 'Two pumpkins? I will pay eight coins!',
    wants: { pumpkin: 2 }, coins: 8, teach: 'comparing bigger number' },
  { id: 'maple_carrots_five', npc: 'maple', band: 'younger', text: 'Five carrots, two coins each! Count by twos!',
    wants: { carrot: 5 }, coins: 10, teach: 'skip-counting by 2s' },
  { id: 'pip_carrot_wheat', npc: 'pip', band: 'younger', text: 'One carrot and two wheat, please!',
    wants: { carrot: 1, wheat: 2 }, coins: 5, teach: 'adding within 20' },
  { id: 'pip_sunberries', npc: 'pip', band: 'older', text: 'Four sunberries! How many coins?',
    wants: { sunberry: 4 }, coins: 12, teach: 'multiplication facts' },
  { id: 'maple_dewmelons', npc: 'maple', band: 'older', text: 'Nine coins for three dewmelons. How much is each?',
    wants: { dewmelon: 3 }, coins: 9, teach: 'division facts' },
  { id: 'pip_glowleaf_half', npc: 'pip', band: 'older', text: 'Half my basket of glowleaf, please!',
    wants: { glowleaf: 4 }, coins: 18, teach: 'fractions of a basket' },
  { id: 'maple_pumpkin_compare', npc: 'maple', band: 'older', text: 'Is four pumpkins worth twelve coins?',
    wants: { pumpkin: 4 }, coins: 12, teach: 'comparing bundle value' },
  { id: 'reed_wheat_save', npc: 'reed', band: 'older', text: 'Save ten wheat for a big reward!',
    wants: { wheat: 10 }, coins: 25, teach: 'is it worth saving for' },
];

export const QUESTIONS = [
  { id: 'g2_add_01', grade: 2, prompt: 'Pip has 4 carrots and picks 3 more. How many now?',
    choices: ['6', '7', '8'], answerIndex: 1, hint: 'Count up from 4: 5, 6, 7.',
    outcome: 'Alberta Math Gr 2: addition within 20' },
  { id: 'g2_add_02', grade: 2, prompt: 'You have 6 sunberries and find 5 more. How many total?',
    choices: ['10', '11', '12'], answerIndex: 1, hint: 'Count up from 6: 7, 8, 9, 10, 11.',
    outcome: 'Alberta Math Gr 2: addition within 20' },
  { id: 'g2_add_03', grade: 2, prompt: 'Reed sees 8 wheat bundles and adds 7 more. How many?',
    choices: ['14', '15', '16'], answerIndex: 1, hint: 'Count up from 8: 9, 10, 11, 12, 13, 14, 15.',
    outcome: 'Alberta Math Gr 2: addition within 20' },
  { id: 'g2_sub_01', grade: 2, prompt: 'You grow 9 pumpkins and sell 4. How many are left?',
    choices: ['4', '5', '6'], answerIndex: 1, hint: 'Count back from 9: 8, 7, 6, 5.',
    outcome: 'Alberta Math Gr 2: subtraction within 20' },
  { id: 'g2_sub_02', grade: 2, prompt: 'Maple had 12 coins and spent 5. How many left?',
    choices: ['6', '7', '8'], answerIndex: 1, hint: 'Count back from 12: 11, 10, 9, 8, 7.',
    outcome: 'Alberta Math Gr 2: subtraction within 20' },
  { id: 'g2_sub_03', grade: 2, prompt: 'Pip plants 15 seeds and 8 sprout. How many did not sprout?',
    choices: ['6', '7', '8'], answerIndex: 1, hint: 'Subtract: 15 minus 8 is 7.',
    outcome: 'Alberta Math Gr 2: subtraction within 20' },
  { id: 'g2_skip_01', grade: 2, prompt: 'Skip-count by 2s: 2, 4, 6, __?',
    choices: ['7', '8', '9'], answerIndex: 1, hint: 'Add 2 each time: 6 plus 2 is 8.',
    outcome: 'Alberta Math Gr 2: skip-counting by 2s' },
  { id: 'g2_skip_02', grade: 2, prompt: 'Skip-count by 5s: 5, 10, 15, __?',
    choices: ['18', '20', '25'], answerIndex: 1, hint: 'Add 5 each time: 15 plus 5 is 20.',
    outcome: 'Alberta Math Gr 2: skip-counting by 5s' },
  { id: 'g2_skip_03', grade: 2, prompt: 'Skip-count by 10s: 10, 20, 30, __?',
    choices: ['35', '40', '50'], answerIndex: 1, hint: 'Add 10 each time: 30 plus 10 is 40.',
    outcome: 'Alberta Math Gr 2: skip-counting by 10s' },
  { id: 'g2_pv_01', grade: 2, prompt: 'How many tens are in the number 47?',
    choices: ['3', '4', '5'], answerIndex: 1, hint: 'The tens digit is 4, so there are 4 tens.',
    outcome: 'Alberta Math Gr 2: place value to 100' },
  { id: 'g2_pv_02', grade: 2, prompt: 'What is the ones digit of 63?',
    choices: ['2', '3', '6'], answerIndex: 1, hint: 'The last digit is the ones digit.',
    outcome: 'Alberta Math Gr 2: place value to 100' },
  { id: 'g2_money_01', grade: 2, prompt: 'You have 3 coins and find 4 more. How many coins?',
    choices: ['6', '7', '8'], answerIndex: 1, hint: 'Add: 3 plus 4 is 7.',
    outcome: 'Alberta Math Gr 2: money counting' },
  { id: 'g5_mult_01', grade: 5, prompt: 'Pip sells 7 carrots at 3 coins each. How many coins?',
    choices: ['18', '21', '24'], answerIndex: 1, hint: 'Multiply: 7 times 3 is 21.',
    outcome: 'Alberta Math Gr 5: multi-digit multiplication' },
  { id: 'g5_mult_02', grade: 5, prompt: 'A crate holds 6 rows of 8 pumpkins. How many total?',
    choices: ['42', '48', '54'], answerIndex: 1, hint: 'Multiply: 6 times 8 is 48.',
    outcome: 'Alberta Math Gr 5: multiplication facts to 81' },
  { id: 'g5_mult_03', grade: 5, prompt: 'Maple packs 9 boxes with 7 sunberries each. How many?',
    choices: ['56', '63', '72'], answerIndex: 1, hint: 'Multiply: 9 times 7 is 63.',
    outcome: 'Alberta Math Gr 5: multiplication facts to 81' },
  { id: 'g5_div_01', grade: 5, prompt: '17 carrots shared among 3 friends. How many left over?',
    choices: ['1', '2', '3'], answerIndex: 1, hint: '17 divided by 3 is 5 remainder 2.',
    outcome: 'Alberta Math Gr 5: division with remainders' },
  { id: 'g5_div_02', grade: 5, prompt: '23 glowleaf split into 4 baskets. What is the remainder?',
    choices: ['2', '3', '4'], answerIndex: 1, hint: '23 divided by 4 is 5 remainder 3.',
    outcome: 'Alberta Math Gr 5: division with remainders' },
  { id: 'g5_div_03', grade: 5, prompt: '31 coins shared equally among 6 creatures. Left over?',
    choices: ['0', '1', '2'], answerIndex: 1, hint: '31 divided by 6 is 5 remainder 1.',
    outcome: 'Alberta Math Gr 5: division with remainders' },
  { id: 'g5_frac_01', grade: 5, prompt: 'Half of 12 wheat bundles is how many?',
    choices: ['5', '6', '7'], answerIndex: 1, hint: 'Half of 12 is 12 divided by 2, which is 6.',
    outcome: 'Alberta Math Gr 5: fractions' },
  { id: 'g5_frac_02', grade: 5, prompt: 'One quarter of 20 coins is how many?',
    choices: ['4', '5', '6'], answerIndex: 1, hint: 'One quarter of 20 is 20 divided by 4, which is 5.',
    outcome: 'Alberta Math Gr 5: fractions' },
  { id: 'g5_frac_03', grade: 5, prompt: 'Which fraction equals one half: 2/4, 3/5, or 2/3?',
    choices: ['2/4', '3/5', '2/3'], answerIndex: 0, hint: 'Simplify 2/4: both divide by 2, giving 1/2.',
    outcome: 'Alberta Math Gr 5: equivalent fractions' },
  { id: 'g5_frac_04', grade: 5, prompt: 'Which fraction equals two thirds: 4/6, 3/4, or 2/5?',
    choices: ['4/6', '3/4', '2/5'], answerIndex: 0, hint: 'Simplify 4/6: both divide by 2, giving 2/3.',
    outcome: 'Alberta Math Gr 5: equivalent fractions' },
  { id: 'g5_dec_01', grade: 5, prompt: 'What is one half written as a decimal?',
    choices: ['0.25', '0.5', '0.75'], answerIndex: 1, hint: 'One divided by two equals zero point five.',
    outcome: 'Alberta Math Gr 5: decimals' },
  { id: 'g5_dec_02', grade: 5, prompt: 'You spend 0.75 of 4 coins. How many coins is that?',
    choices: ['2', '3', '4'], answerIndex: 1, hint: 'Three quarters of 4: multiply 0.75 by 4 to get 3.',
    outcome: 'Alberta Math Gr 5: decimals' },
];

export const DIALOG = {
  pip: ['Nice harvest!', 'That egg is wiggling!', 'Coins for your crops!', 'Welcome to the market!', 'What a fine day to farm!'],
  maple: ['Your farm is growing!', 'I love dewmelons!', 'Creatures are so cute!', 'The sun feels nice today!', 'You are doing great!'],
  reed: ['Let us explore!', 'I spotted something shiny!', 'Every creature is special!', 'The farm is full of surprises!', 'Ready for an adventure?'],
};
