// Learning questions (used by the help-along timer acceleration).
export const QUESTIONS = [
  { id: 'g2_add_01', grade: 2, prompt: 'Pip has 4 carrots and picks 3 more. How many now?',
    choices: ['6', '7', '8'], answerIndex: 1, hint: 'Count up from 4: 5, 6, 7.',
    outcome: 'Alberta Math Gr 2: addition within 20' },
  { id: 'g2_add_02', grade: 2, prompt: 'You have 6 sunberries and find 5 more. How many total?',
    choices: ['10', '11', '12'], answerIndex: 1, hint: 'Count up from 6: 7, 8, 9, 10, 11.',
    outcome: 'Alberta Math Gr 2: addition within 20' },
  { id: 'g2_add_03', grade: 2, prompt: 'Reed sees 8 wheat bundles and adds 7 more. How many?',
    choices: ['14', '15', '16'], answerIndex: 1, hint: 'Count up from 8: 9, 10, 11, 12, 13, 14, 15.',
    outcome: 'Alberta Math Gr 2: addition within 20' },
  { id: 'g2_sub_01', grade: 2, prompt: 'You grow 9 pumpkins and sell 4. How many are left?',
    choices: ['4', '5', '6'], answerIndex: 1, hint: 'Count back from 9: 8, 7, 6, 5.',
    outcome: 'Alberta Math Gr 2: subtraction within 20' },
  { id: 'g2_sub_02', grade: 2, prompt: 'Maple had 12 coins and spent 5. How many left?',
    choices: ['6', '7', '8'], answerIndex: 1, hint: 'Count back from 12: 11, 10, 9, 8, 7.',
    outcome: 'Alberta Math Gr 2: subtraction within 20' },
  { id: 'g2_sub_03', grade: 2, prompt: 'Pip plants 15 seeds and 8 sprout. How many did not sprout?',
    choices: ['6', '7', '8'], answerIndex: 1, hint: 'Subtract: 15 minus 8 is 7.',
    outcome: 'Alberta Math Gr 2: subtraction within 20' },
  { id: 'g2_skip_01', grade: 2, prompt: 'Skip-count by 2s: 2, 4, 6, __?',
    choices: ['7', '8', '9'], answerIndex: 1, hint: 'Add 2 each time: 6 plus 2 is 8.',
    outcome: 'Alberta Math Gr 2: skip-counting by 2s' },
  { id: 'g2_skip_02', grade: 2, prompt: 'Skip-count by 5s: 5, 10, 15, __?',
    choices: ['18', '20', '25'], answerIndex: 1, hint: 'Add 5 each time: 15 plus 5 is 20.',
    outcome: 'Alberta Math Gr 2: skip-counting by 5s' },
  { id: 'g2_skip_03', grade: 2, prompt: 'Skip-count by 10s: 10, 20, 30, __?',
    choices: ['35', '40', '50'], answerIndex: 1, hint: 'Add 10 each time: 30 plus 10 is 40.',
    outcome: 'Alberta Math Gr 2: skip-counting by 10s' },
  { id: 'g2_pv_01', grade: 2, prompt: 'How many tens are in the number 47?',
    choices: ['3', '4', '5'], answerIndex: 1, hint: 'The tens digit is 4, so there are 4 tens.',
    outcome: 'Alberta Math Gr 2: place value to 100' },
  { id: 'g2_pv_02', grade: 2, prompt: 'What is the ones digit of 63?',
    choices: ['2', '3', '6'], answerIndex: 1, hint: 'The last digit is the ones digit.',
    outcome: 'Alberta Math Gr 2: place value to 100' },
  { id: 'g2_money_01', grade: 2, prompt: 'You have 3 coins and find 4 more. How many coins?',
    choices: ['6', '7', '8'], answerIndex: 1, hint: 'Add: 3 plus 4 is 7.',
    outcome: 'Alberta Math Gr 2: money counting' },
  { id: 'g5_mult_01', grade: 5, prompt: 'Pip sells 7 carrots at 3 coins each. How many coins?',
    choices: ['18', '21', '24'], answerIndex: 1, hint: 'Multiply: 7 times 3 is 21.',
    outcome: 'Alberta Math Gr 5: multi-digit multiplication' },
  { id: 'g5_mult_02', grade: 5, prompt: 'A crate holds 6 rows of 8 pumpkins. How many total?',
    choices: ['42', '48', '54'], answerIndex: 1, hint: 'Multiply: 6 times 8 is 48.',
    outcome: 'Alberta Math Gr 5: multiplication facts to 81' },
  { id: 'g5_mult_03', grade: 5, prompt: 'Maple packs 9 boxes with 7 sunberries each. How many?',
    choices: ['56', '63', '72'], answerIndex: 1, hint: 'Multiply: 9 times 7 is 63.',
    outcome: 'Alberta Math Gr 5: multiplication facts to 81' },
  { id: 'g5_div_01', grade: 5, prompt: '17 carrots shared among 3 friends. How many left over?',
    choices: ['1', '2', '3'], answerIndex: 1, hint: '17 divided by 3 is 5 remainder 2.',
    outcome: 'Alberta Math Gr 5: division with remainders' },
  { id: 'g5_div_02', grade: 5, prompt: '23 glowleaf split into 4 baskets. What is the remainder?',
    choices: ['2', '3', '4'], answerIndex: 1, hint: '23 divided by 4 is 5 remainder 3.',
    outcome: 'Alberta Math Gr 5: division with remainders' },
  { id: 'g5_div_03', grade: 5, prompt: '31 coins shared equally among 6 creatures. Left over?',
    choices: ['0', '1', '2'], answerIndex: 1, hint: '31 divided by 6 is 5 remainder 1.',
    outcome: 'Alberta Math Gr 5: division with remainders' },
  { id: 'g5_frac_01', grade: 5, prompt: 'Half of 12 wheat bundles is how many?',
    choices: ['5', '6', '7'], answerIndex: 1, hint: 'Half of 12 is 12 divided by 2, which is 6.',
    outcome: 'Alberta Math Gr 5: fractions' },
  { id: 'g5_frac_02', grade: 5, prompt: 'One quarter of 20 coins is how many?',
    choices: ['4', '5', '6'], answerIndex: 1, hint: 'One quarter of 20 is 20 divided by 4, which is 5.',
    outcome: 'Alberta Math Gr 5: fractions' },
  { id: 'g5_frac_03', grade: 5, prompt: 'Which fraction equals one half: 2/4, 3/5, or 2/3?',
    choices: ['2/4', '3/5', '2/3'], answerIndex: 0, hint: 'Simplify 2/4: both divide by 2, giving 1/2.',
    outcome: 'Alberta Math Gr 5: equivalent fractions' },
  { id: 'g5_frac_04', grade: 5, prompt: 'Which fraction equals two thirds: 4/6, 3/4, or 2/5?',
    choices: ['4/6', '3/4', '2/5'], answerIndex: 0, hint: 'Simplify 4/6: both divide by 2, giving 2/3.',
    outcome: 'Alberta Math Gr 5: equivalent fractions' },
  { id: 'g5_dec_01', grade: 5, prompt: 'What is one half written as a decimal?',
    choices: ['0.25', '0.5', '0.75'], answerIndex: 1, hint: 'One divided by two equals zero point five.',
    outcome: 'Alberta Math Gr 5: decimals' },
  { id: 'g5_dec_02', grade: 5, prompt: 'You spend 0.75 of 4 coins. How many coins is that?',
    choices: ['2', '3', '4'], answerIndex: 1, hint: 'Three quarters of 4: multiply 0.75 by 4 to get 3.',
    outcome: 'Alberta Math Gr 5: decimals' },
];
