"""The binary gates from docs/foundry/topology/QUALIFICATION.md, as functions.

Each gate returns a dict with `id`, `passed`, and enough detail to act on a failure. No gate returns
a bare boolean: "G9 failed" is useless, "G9 failed, 3 poles inside DEF_Shoulder at these coordinates"
is actionable.

Run inside Blender (needs bpy/bmesh/mathutils). Split from qualify.py so the logic can be exercised
against fixtures without a CLI in the way.

Two rules this file follows, both learned the hard way in this repo:

1. A gate that cannot fail is worse than no gate. Every one of these is exercised against a
   deliberately broken fixture, and the broken fixture is generated by script so the proof is
   reproducible rather than a claim in a commit message.
2. Where a check is a heuristic rather than a measurement, it says so in its own output. G11 (T-pose)
   is the honest example: no script can confirm intent, only that the arms are roughly horizontal.
"""

import re
from collections import defaultdict

import bmesh
import bpy
from mathutils import Vector

# Three.js stores skin weights in a Vector4 and its transform path loops i<4. A fifth influence is
# dropped SILENTLY at runtime — no error, no warning, just a vertex that deforms wrongly. Stage T
# measured a shipped professional pack breaking this on 29% of one mesh's vertices, so tooling cannot
# be assumed to respect it.
MAX_INFLUENCES = 4

# Weight sums this far from 1.0 are treated as unnormalised.
WEIGHT_EPS = 1e-4

# Below this, a face has no meaningful area and produces NaN normals.
DEGENERATE_AREA = 1e-9

# Vertices closer together than this are treated as doubled.
DOUBLE_DIST = 1e-6

NAME_OK = re.compile(r"^[A-Za-z][A-Za-z0-9_]*$")

BONE_LAYER_PREFIXES = ("DEF_", "CTRL_", "MCH_")

# The deform layer's prefix. Deformation *zones* are not derived from these groups — see
# influence_counts() and joint_zones() for why that definition was wrong.
DEFORM_PREFIX = "DEF_"


def _result(gate_id, passed, summary, **detail):
    out = {"id": gate_id, "passed": bool(passed), "summary": summary}
    out.update(detail)
    return out


def _bm(mesh_obj):
    bm = bmesh.new()
    bm.from_mesh(mesh_obj.data)
    bm.verts.ensure_lookup_table()
    bm.edges.ensure_lookup_table()
    bm.faces.ensure_lookup_table()
    return bm


# ── 1.1 Mesh integrity ────────────────────────────────────────────────────────────────────────────


def g1_manifold(mesh_obj):
    """Closed and manifold, with the three failure kinds reported separately.

    A disk with a boundary is manifold-*with-boundary*, so lumping boundary edges in with
    three-face edges under one "non-manifold" label would be imprecise. G1's actual requirement is
    "no holes except by deliberate, documented design", so each kind is counted on its own and the
    candidate's author can point at a documented hole if they have one.
    """
    bm = _bm(mesh_obj)
    try:
        boundary = [e.index for e in bm.edges if len(e.link_faces) == 1]
        excess = [e.index for e in bm.edges if len(e.link_faces) > 2]
        wire = [e.index for e in bm.edges if len(e.link_faces) == 0]
        loose = [v.index for v in bm.verts if not v.link_faces]
        passed = not (boundary or excess or wire or loose)
        return _result(
            "G1",
            passed,
            "closed and manifold"
            if passed
            else (
                f"{len(boundary)} boundary edges, {len(excess)} edges shared by 3+ faces, "
                f"{len(wire)} wire edges, {len(loose)} loose verts"
            ),
            boundaryEdges=boundary[:20],
            edgesWithThreeOrMoreFaces=excess[:20],
            wireEdges=wire[:20],
            looseVerts=loose[:20],
        )
    finally:
        bm.free()


def g2_no_degenerate_faces(mesh_obj):
    bm = _bm(mesh_obj)
    try:
        bad = [f.index for f in bm.faces if f.calc_area() < DEGENERATE_AREA]
        return _result(
            "G2",
            not bad,
            "no zero-area faces" if not bad else f"{len(bad)} zero-area faces",
            faces=bad[:20],
        )
    finally:
        bm.free()


def g3_no_doubled_verts(mesh_obj):
    bm = _bm(mesh_obj)
    try:
        # Bucket by rounded position; only compare within a bucket. O(n) rather than O(n^2), which
        # matters because this runs on every stress pose.
        buckets = defaultdict(list)
        q = 1.0 / max(DOUBLE_DIST, 1e-12)
        for v in bm.verts:
            key = (round(v.co.x * q), round(v.co.y * q), round(v.co.z * q))
            buckets[key].append(v.index)
        dupes = [idxs for idxs in buckets.values() if len(idxs) > 1]
        return _result(
            "G3",
            not dupes,
            "no doubled verts" if not dupes else f"{len(dupes)} positions with more than one vert",
            positions=dupes[:20],
        )
    finally:
        bm.free()


def g4_consistent_normals(mesh_obj):
    """Recalculate normals on a copy and report which faces the recalculation flipped.

    There is no absolute 'correct' normal for an arbitrary surface, but there IS a consistent
    orientation for a closed one. Any face that recalc flips was inconsistent with its neighbours.
    """
    bm = _bm(mesh_obj)
    try:
        before = [f.normal.copy() for f in bm.faces]
        bmesh.ops.recalc_face_normals(bm, faces=bm.faces)
        bm.faces.ensure_lookup_table()
        flipped = [i for i, n in enumerate(before) if n.dot(bm.faces[i].normal) < 0.0]
        return _result(
            "G4",
            not flipped,
            "normals consistent" if not flipped else f"{len(flipped)} faces have inverted normals",
            faces=flipped[:20],
        )
    finally:
        bm.free()


def g5_no_ngons(mesh_obj):
    bm = _bm(mesh_obj)
    try:
        bad = [f.index for f in bm.faces if len(f.verts) > 4]
        return _result(
            "G5",
            not bad,
            "no n-gons" if not bad else f"{len(bad)} faces with more than 4 verts",
            faces=bad[:20],
        )
    finally:
        bm.free()


def g6_no_self_intersection(mesh_obj):
    """Self-intersection, checked per pose. Geometry passing through itself is a deformation failure.

    Triangulates a copy, builds a BVH tree, and overlaps it with itself. Triangle-triangle
    intersection is `mathutils`' own test — a documented API rather than an addon that may not be
    enabled, and not something worth reimplementing.

    **Face pairs that share a vertex are excluded.** Two triangles meeting at an edge or corner
    touch by construction; counting them would report every mesh as self-intersecting and make the
    gate useless. The exclusion is on shared *vertices*, which is the adjacency relation, not a
    distance fudge.
    """
    from mathutils.bvhtree import BVHTree

    bm = _bm(mesh_obj)
    try:
        # Keep the map from each triangle back to the face it came from, so a failure names the
        # original quad rather than a tessellation artifact the author never authored.
        tri_to_face = {}
        original = {f: f.index for f in bm.faces}
        res = bmesh.ops.triangulate(bm, faces=bm.faces[:])
        bm.faces.ensure_lookup_table()
        for f in bm.faces:
            src = res["face_map"].get(f, f)
            tri_to_face[f.index] = original.get(src, original.get(f, f.index))

        verts_of = {f.index: frozenset(v.index for v in f.verts) for f in bm.faces}
        tree = BVHTree.FromBMesh(bm)
        pairs = set()
        for a, b in tree.overlap(tree):
            if a == b:
                continue
            if verts_of[a] & verts_of[b]:
                continue  # adjacent by construction, not an intersection
            pairs.add((min(a, b), max(a, b)))

        # Re-normalise after mapping triangles back to faces. Two triangles of face A can each hit a
        # different triangle of face B, and without min/max here the same face pair is reported twice
        # in both orderings — which inflates the count and makes a small fold look like a big one.
        reported = sorted({
            (min(tri_to_face[a], tri_to_face[b]), max(tri_to_face[a], tri_to_face[b]))
            for a, b in pairs
        })
        return _result(
            "G6",
            not reported,
            "no self-intersection" if not reported else f"{len(reported)} intersecting face pairs",
            facePairs=[list(p) for p in reported[:20]],
        )
    finally:
        bm.free()


# ── 1.2 Deforming topology ────────────────────────────────────────────────────────────────────────


def influence_counts(mesh_obj, armature_obj):
    """How many deform bones actually move each vertex. Keyed by vertex index.

    This is the load-bearing definition in the whole file. A vertex weighted 1.0 to a single bone
    moves **rigidly** with that bone — it is carried, not deformed. A vertex whose weights are split
    across two or more bones is where the surface actually has to stretch.

    So "the deforming part of the mesh" is measurable from the weights, and does not need anybody's
    opinion about which polygons look like a joint.
    """
    return {i: len(pairs) for i, pairs in enumerate(_vertex_weights(mesh_obj, armature_obj))}


def declared_loops(manifest):
    """The joint loops the candidate declares, from its topology manifest."""
    return {name: [int(i) for i in verts] for name, verts in (manifest or {}).get("loops", {}).items()}


def joint_zones(mesh_obj, manifest):
    """Each declared loop, widened by one ring of neighbours.

    A pole sitting immediately beside a joint loop pinches just as badly as one on it, and widening
    by exactly one ring also means a candidate cannot dodge G9 by declaring a loop one edge away
    from its own poles.
    """
    loops = declared_loops(manifest)
    if not loops:
        return {}
    bm = _bm(mesh_obj)
    try:
        limit = len(bm.verts)
        zones = {}
        for name, verts in loops.items():
            widened = set()
            for i in verts:
                if 0 <= i < limit:
                    widened.add(i)
                    v = bm.verts[i]
                    widened.update(e.other_vert(v).index for e in v.link_edges)
            zones[name] = widened
        return zones
    finally:
        bm.free()


def g7_quads_where_it_deforms(mesh_obj, armature_obj, manifest):
    """Quads wherever the surface deforms. Triangles only in rigid, declared places.

    QUALIFICATION.md G7 says "anything that deforms is quads; triangles only in static, documented
    places". The checkable form of "static" is `influence_counts` above: a triangle whose every
    vertex has exactly one influence is carried rigidly by one bone and never stretches.

    An earlier version of this gate demanded 100% quads. That was **stricter than the bar it was
    meant to enforce** and would have failed a candidate the document permits.
    """
    infl = influence_counts(mesh_obj, armature_obj)
    declared = (manifest or {}).get("documentedStaticTriangles") or {}
    bm = _bm(mesh_obj)
    try:
        counts = defaultdict(int)
        tris, deforming_tris = [], []
        for f in bm.faces:
            counts[len(f.verts)] += 1
            if len(f.verts) == 3:
                tris.append(f.index)
                if any(infl.get(v.index, 0) > 1 for v in f.verts):
                    deforming_tris.append(f.index)
        total = sum(counts.values())
        ratio = (counts.get(4, 0) / total) if total else 0.0

        problems = []
        if deforming_tris:
            problems.append(f"{len(deforming_tris)} triangles have a vertex with blended weights")
        if tris and not declared:
            problems.append(f"{len(tris)} triangles exist but the manifest declares no static triangles")
        if total == 0:
            problems.append("the mesh has no faces")

        return _result(
            "G7",
            not problems,
            f"quad ratio {ratio:.4f} over {total} faces, {len(tris)} triangles all rigid"
            if not problems
            else "; ".join(problems),
            faceCounts={str(k): v for k, v in sorted(counts.items())},
            quadRatio=round(ratio, 6),
            triangles=len(tris),
            trianglesTouchingBlendedWeights=deforming_tris[:20],
            declaredStaticTriangles=sorted(declared.keys()),
        )
    finally:
        bm.free()


def g8_declared_joint_loops(mesh_obj, armature_obj, manifest):
    """Every declared joint loop is a real closed cycle, sitting where the weights actually blend.

    Spec section 13 rejects building an edge-loop *detector* — a perfect one would yield facts about
    someone else's mesh, not the recipe that made it deform well. So this does not go looking for
    loops. The candidate **declares** its loops in its manifest, and this gate verifies the
    declaration against the mesh:

    - every index exists;
    - every vertex in a loop has exactly two edges to other vertices of the same loop, so the
      declaration is a union of closed cycles rather than an arbitrary bag of vertices;
    - every vertex in a loop has blended weights, so the loop is at a joint rather than parked
      somewhere harmless to make the gate pass.

    That last check is what stops the declaration being self-serving.

    **Recorded, not gating:** every pair of deform bones that share blended vertices — the joints the
    *weights* say exist — and whether each has a declared loop. An undeclared joint is therefore
    visible in the report without this gate inventing a rule about how many loops a region owes.
    """
    loops = declared_loops(manifest)
    if not loops:
        return _result(
            "G8",
            False,
            "the manifest declares no joint loops, so there is nothing to verify. Reported as a "
            "failure on purpose: a gate with no input must not read as a pass.",
            loops={},
        )

    infl = influence_counts(mesh_obj, armature_obj)
    weights = _vertex_weights(mesh_obj, armature_obj)
    bm = _bm(mesh_obj)
    try:
        limit = len(bm.verts)
        detail, problems = {}, []
        for name, verts in sorted(loops.items()):
            missing = [i for i in verts if not (0 <= i < limit)]
            members = set(i for i in verts if 0 <= i < limit)
            degrees = {
                i: sum(1 for e in bm.verts[i].link_edges if e.other_vert(bm.verts[i]).index in members)
                for i in members
            }
            not_two = sorted(i for i, d in degrees.items() if d != 2)
            rigid = sorted(i for i in members if infl.get(i, 0) < 2)
            detail[name] = {
                "verts": len(verts),
                "cycleComponents": _cycle_components(bm, members),
                "verticesNotDegreeTwo": not_two[:20],
                "verticesWithoutBlendedWeights": rigid[:20],
                "missingIndices": missing[:20],
            }
            if missing:
                problems.append(f"{name} names {len(missing)} vertices that do not exist")
            if not_two:
                problems.append(f"{name} is not a closed cycle: {len(not_two)} vertices are not degree 2")
            if rigid:
                problems.append(f"{name} has {len(rigid)} vertices with no blended weights, so it is not at a joint")

        return _result(
            "G8",
            not problems,
            f"{len(loops)} declared joint loops are closed cycles at blended weights"
            if not problems
            else "; ".join(problems),
            loops=detail,
            jointsTheWeightsImply=_blended_bone_pairs(weights),
            note="The bone pairs are recorded, not gated. An undeclared joint shows up here without "
            "this gate inventing a quota for how many loops a region owes.",
        )
    finally:
        bm.free()


def _cycle_components(bm, members):
    """How many connected pieces the declared vertices form. Several closed loops is legitimate."""
    seen, components = set(), 0
    for start in sorted(members):
        if start in seen:
            continue
        components += 1
        stack = [start]
        while stack:
            i = stack.pop()
            if i in seen:
                continue
            seen.add(i)
            v = bm.verts[i]
            stack.extend(
                e.other_vert(v).index
                for e in v.link_edges
                if e.other_vert(v).index in members and e.other_vert(v).index not in seen
            )
    return components


def _blended_bone_pairs(weights):
    """Bone pairs that share blended vertices — the joints the weights imply, whatever was declared."""
    tally = defaultdict(int)
    for pairs in weights:
        names = sorted(name for name, _ in pairs)
        for a in range(len(names)):
            for b in range(a + 1, len(names)):
                tally[(names[a], names[b])] += 1
    return [{"bones": list(k), "sharedVerts": v} for k, v in sorted(tally.items(), key=lambda kv: -kv[1])]


def _poles(bm, vert_indices=None):
    out = []
    for v in bm.verts:
        if vert_indices is not None and v.index not in vert_indices:
            continue
        valence = len(v.link_edges)
        # Boundary verts legitimately have fewer edges; only interior verts are judged.
        if any(not e.is_manifold for e in v.link_edges):
            continue
        if valence != 4:
            out.append((v.index, valence))
    return out


def g9_no_poles_in_joint_zones(mesh_obj, armature_obj, manifest):
    """No pole on or beside a declared joint loop.

    An earlier version treated a whole `DEF_` vertex group as the deformation zone. That was
    **unsatisfiable**: `DEF_Head` covers the entire head, a closed head must have poles somewhere by
    Euler's formula, so no valid mesh could ever have passed. A gate no correct mesh can satisfy is
    as useless as one nothing can fail, and the torus fixture was too kind to reveal it.
    """
    zones = joint_zones(mesh_obj, manifest)
    if not zones:
        return _result(
            "G9",
            False,
            "the manifest declares no joint loops, so there are no zones to check. Reported as a "
            "failure on purpose.",
            zones={},
        )
    bm = _bm(mesh_obj)
    try:
        detail, passed = {}, True
        for name, verts in sorted(zones.items()):
            found = _poles(bm, verts)
            detail[name] = {
                "zoneVerts": len(verts),
                "poles": [{"vert": i, "valence": val} for i, val in found[:20]],
            }
            if found:
                passed = False
        return _result(
            "G9",
            passed,
            "no poles on or beside any declared joint loop"
            if passed
            else "poles found in a joint zone",
            zones=detail,
        )
    finally:
        bm.free()


def g10_pole_kinds(mesh_obj, armature_obj, manifest):
    """5-poles in preference to 3-poles where a pole is unavoidable.

    The binary part is narrow and deliberate: **no valence-3 pole in a joint zone.** Poles elsewhere
    are counted and reported, not judged.

    An earlier version failed a candidate whose 3-poles merely outnumbered its 5-poles. That ratio
    was an absolute threshold invented here, which is the one thing QUALIFICATION.md's governing rule
    forbids — and it would have failed a mesh whose 3-poles all sat in rigid caps, which is exactly
    where a 3-pole is harmless.

    Note the binary part is redundant with G9, which bans poles of every kind in a joint zone. That
    is on purpose: if G9's zone definition is ever loosened, the prohibition on the worse *kind* of
    pole survives on its own.
    """
    zones = joint_zones(mesh_obj, manifest)
    in_zone = set().union(*zones.values()) if zones else set()
    bm = _bm(mesh_obj)
    try:
        found = _poles(bm)
        inside = [(i, val) for i, val in found if i in in_zone]
        threes_inside = [i for i, val in inside if val == 3]
        counted = defaultdict(int)
        for _, val in found:
            counted[val] += 1
        passed = not threes_inside
        return _result(
            "G10",
            passed,
            f"{counted.get(3, 0)} three-poles, {counted.get(5, 0)} five-poles, "
            f"{sum(v for k, v in counted.items() if k not in (3, 5))} other, "
            f"{len(inside)} of them in a joint zone"
            if passed
            else f"{len(threes_inside)} three-poles sit in a joint zone",
            polesByValence={str(k): v for k, v in sorted(counted.items())},
            polesInJointZones=[{"vert": i, "valence": val} for i, val in inside[:20]],
            threePolesInJointZones=threes_inside[:20],
            note="Counts outside joint zones are recorded, not gated. No ratio threshold is invented here.",
        )
    finally:
        bm.free()


# ── 1.3 Rig and weights ───────────────────────────────────────────────────────────────────────────


def g11_t_pose(armature_obj):
    """HEURISTIC. No script can confirm a rest pose was intended as a T-pose.

    What it can confirm: bones whose names suggest upper arms point roughly along world X. That is
    reported as a heuristic in its own output so nobody quotes it as proof of a T-pose.
    """
    arm = armature_obj.data
    candidates = [
        b
        for b in arm.bones
        if any(t in b.name.lower() for t in ("upperarm", "upper_arm", "shoulder", "arm"))
        and "fore" not in b.name.lower()
    ]
    if not candidates:
        return _result(
            "G11", False, "no bone name suggests an upper arm, so the pose cannot be checked",
            heuristic=True,
        )
    detail = []
    passed = True
    for b in candidates:
        direction = (b.tail_local - b.head_local)
        if direction.length == 0:
            passed = False
            detail.append({"bone": b.name, "error": "zero-length bone"})
            continue
        direction.normalize()
        horizontality = abs(direction.dot(Vector((1.0, 0.0, 0.0))))
        detail.append({"bone": b.name, "alignmentToWorldX": round(horizontality, 4)})
        if horizontality < 0.85:
            passed = False
    return _result(
        "G11",
        passed,
        "arm bones are roughly horizontal" if passed else "arm bones are not horizontal",
        bones=detail,
        heuristic=True,
        note="A-pose deforms shoulders better than T-pose. T-pose is kept for retargeting; see QUALIFICATION.md.",
    )


def g12_root_bone(armature_obj):
    arm = armature_obj.data
    roots = [b for b in arm.bones if b.parent is None]
    problems = []
    if len(roots) != 1:
        problems.append(f"{len(roots)} root bones, expected exactly 1")
    root = roots[0] if roots else None
    if root is not None:
        if root.name != "Root":
            problems.append(f'root bone is named "{root.name}", expected "Root"')
        if root.head_local.length > 1e-6:
            problems.append(f"root head is at {tuple(round(c, 6) for c in root.head_local)}, not the origin")
    return _result(
        "G12",
        not problems,
        "single Root bone at the origin" if not problems else "; ".join(problems),
        rootNames=[b.name for b in roots],
    )


def g13_bone_layer_naming(armature_obj):
    bad = [b.name for b in armature_obj.data.bones if not b.name.startswith(BONE_LAYER_PREFIXES) and b.name != "Root"]
    return _result(
        "G13",
        not bad,
        "every bone carries a layer prefix"
        if not bad
        else f"{len(bad)} bones have no DEF_/CTRL_/MCH_ prefix",
        offenders=bad[:20],
    )


def g14_deform_joint_count(armature_obj, expected, region_share_note=""):
    """The contract pins rig.deformJointTarget. Nothing checked it until this gate existed."""
    deform = [b.name for b in armature_obj.data.bones if b.use_deform]
    passed = len(deform) == expected
    return _result(
        "G14",
        passed,
        f"{len(deform)} deform bones, contract expects {expected}",
        deformBones=sorted(deform),
        expected=expected,
        regionShareNote=region_share_note,
    )


def g15_deform_flag_set(armature_obj):
    """A DEF_ bone without the deform flag leaves its vertices unanimated and silently orphaned."""
    bad = [b.name for b in armature_obj.data.bones if b.name.startswith("DEF_") and not b.use_deform]
    also = [b.name for b in armature_obj.data.bones if not b.name.startswith("DEF_") and b.use_deform]
    problems = {}
    if bad:
        problems["defBonesWithoutDeformFlag"] = bad[:20]
    if also:
        problems["nonDefBonesWithDeformFlag"] = also[:20]
    return _result(
        "G15",
        not problems,
        "deform flags match the DEF_ prefix" if not problems else "deform flags disagree with naming",
        **problems,
    )


def g16_unit_armature_scale(armature_obj):
    s = armature_obj.scale
    off = [round(v, 6) for v in s if abs(v - 1.0) > 1e-6]
    return _result(
        "G16",
        not off,
        "armature scale is unit" if not off else f"armature scale is {tuple(round(v, 6) for v in s)}",
        scale=[round(v, 6) for v in s],
    )


def _vertex_weights(mesh_obj, armature_obj):
    """Per-vertex (name, weight) pairs, counting only groups that correspond to deform bones."""
    deform_names = {b.name for b in armature_obj.data.bones if b.use_deform}
    idx_to_name = {g.index: g.name for g in mesh_obj.vertex_groups}
    per_vert = []
    for v in mesh_obj.data.vertices:
        pairs = [
            (idx_to_name[g.group], g.weight)
            for g in v.groups
            if idx_to_name.get(g.group) in deform_names and g.weight > 0.0
        ]
        per_vert.append(pairs)
    return per_vert


def g17_no_zero_weight_verts(mesh_obj, armature_obj):
    per_vert = _vertex_weights(mesh_obj, armature_obj)
    bad = [i for i, pairs in enumerate(per_vert) if not pairs]
    return _result(
        "G17",
        not bad,
        "every vertex is weighted" if not bad else f"{len(bad)} vertices have no weight at all",
        verts=bad[:20],
    )


def g18_influence_cap(mesh_obj, armature_obj):
    per_vert = _vertex_weights(mesh_obj, armature_obj)
    over = [(i, len(pairs)) for i, pairs in enumerate(per_vert) if len(pairs) > MAX_INFLUENCES]
    worst = max((n for _, n in over), default=max((len(p) for p in per_vert), default=0))
    return _result(
        "G18",
        not over,
        f"max {worst} influences per vertex, cap is {MAX_INFLUENCES}",
        cap=MAX_INFLUENCES,
        maxObserved=worst,
        offenders=[{"vert": i, "influences": n} for i, n in over[:20]],
        note="Three.js drops the fifth influence silently. This gate is the only thing that notices.",
    )


def g19_weights_normalised(mesh_obj, armature_obj):
    per_vert = _vertex_weights(mesh_obj, armature_obj)
    bad = []
    for i, pairs in enumerate(per_vert):
        if not pairs:
            continue  # G17's problem, not this one
        total = sum(w for _, w in pairs)
        if abs(total - 1.0) > WEIGHT_EPS:
            bad.append({"vert": i, "sum": round(total, 6)})
    return _result(
        "G19",
        not bad,
        "weights normalised" if not bad else f"{len(bad)} vertices have weights not summing to 1",
        epsilon=WEIGHT_EPS,
        offenders=bad[:20],
    )


def g20_names_exportable(objs):
    bad = []
    for o in objs:
        if not NAME_OK.match(o.name):
            bad.append(o.name)
        if o.type == "ARMATURE":
            bad += [b.name for b in o.data.bones if not NAME_OK.match(b.name)]
        if o.type == "MESH":
            bad += [g.name for g in o.vertex_groups if not NAME_OK.match(g.name)]
    return _result(
        "G20",
        not bad,
        "all names are export-safe" if not bad else f"{len(bad)} names contain special characters",
        offenders=bad[:20],
    )


# ── 1.4 Surface ───────────────────────────────────────────────────────────────────────────────────

# Node types that do not survive glTF export. Blender's viewport renders them happily, which is
# exactly why this needs to be a gate: the failure is invisible until the GLB is in the browser.
GLTF_UNSAFE_NODES = {
    "ShaderNodeValToRGB",  # Color Ramp
    "ShaderNodeTexNoise",
    "ShaderNodeTexVoronoi",
    "ShaderNodeTexMusgrave",
    "ShaderNodeTexWave",
    "ShaderNodeTexMagic",
    "ShaderNodeTexChecker",
    "ShaderNodeTexGradient",
    "ShaderNodeBump",
    "ShaderNodeMixRGB",
    "ShaderNodeMath",
    "ShaderNodeVertexColor",
}


def g21_single_material_and_atlas(mesh_objs, max_atlas_px):
    materials = {m.name for o in mesh_objs for m in o.data.materials if m is not None}
    images = {}
    for name in materials:
        mat = bpy.data.materials.get(name)
        if not mat or not mat.use_nodes:
            continue
        for node in mat.node_tree.nodes:
            if node.type == "TEX_IMAGE" and node.image is not None:
                images[node.image.name] = tuple(node.image.size)
    oversized = {k: v for k, v in images.items() if max(v) > max_atlas_px}
    problems = []
    if len(materials) != 1:
        problems.append(f"{len(materials)} materials, expected exactly 1")
    if len(images) > 1:
        problems.append(f"{len(images)} textures, expected at most 1 atlas")
    if oversized:
        problems.append(f"textures exceed {max_atlas_px}px: {oversized}")
    return _result(
        "G21",
        not problems,
        "one material, one atlas within budget" if not problems else "; ".join(problems),
        materials=sorted(materials),
        textures={k: list(v) for k, v in images.items()},
        maxAtlasPx=max_atlas_px,
    )


def g22_materials_survive_gltf(mesh_objs):
    offenders = []
    for o in mesh_objs:
        for mat in o.data.materials:
            if mat is None or not mat.use_nodes:
                continue
            for node in mat.node_tree.nodes:
                if node.bl_idname in GLTF_UNSAFE_NODES:
                    offenders.append({"material": mat.name, "node": node.bl_idname, "label": node.name})
    return _result(
        "G22",
        not offenders,
        "all materials round-trip to glTF" if not offenders else f"{len(offenders)} nodes are lost on glTF export",
        offenders=offenders[:20],
        note="Blender's viewport renders these fine. The GLB will not.",
    )


def g24_uvs_present(mesh_objs):
    missing = [o.name for o in mesh_objs if not o.data.uv_layers]
    return _result(
        "G24",
        not missing,
        "every mesh has UVs" if not missing else f"{len(missing)} meshes have no UV layer",
        meshes=missing,
    )


def g26_no_shape_keys_yet(mesh_objs):
    """Vertex order must be final before any shape key exists, or shape keys corrupt silently."""
    with_keys = [o.name for o in mesh_objs if o.data.shape_keys is not None]
    return _result(
        "G26",
        not with_keys,
        "no shape keys, so vertex order is still free to change"
        if not with_keys
        else f"{len(with_keys)} meshes already carry shape keys",
        meshes=with_keys,
        note="Not a prohibition on shape keys. It records that geometry must be frozen before they exist.",
    )
